---
- name: clone repository
  git:
    #repo: https://github.com/zhitaop/Hello_world.git
    repo: https://github.com/zhitaop/CCC-Assignment-2-Group-49.git
    dest: /home/ubuntu/project

- name: Run docker compose
  tags: 'wordpress'
  become: yes
  docker_service: 
    project_src: "/home/ubuntu/project"
    #pull: yes
    state: present
    #remove_orphans: yes
    #recreate: always

